// import 'package:cloud_firestore/cloud_firestore.dart';
// import 'package:demo_firebase/FirebaseDemoApp.dart';
// import 'package:demo_firebase/app.dart';
// import 'package:demo_firebase/app2.dart';
// import 'package:demo_firebase/auth/login.dart';
// import 'package:firebase_auth/firebase_auth.dart';
// import 'package:flutter/material.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart';

// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();

//   await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
//   // var instance = FirebaseFirestore.instance;
//   // var credential = await FirebaseAuth.instance.signInWithEmailAndPassword(
//   //   email: "test@gmail.com",
//   //   password: '123456',
//   // );
//   // print('firebase instance {$credential}');
//   // var user = credential.user;
//   // print('firebase.instance: {$user.uid}');
//   // if (user?.emailVerified ?? false) {
//   //   print('user verified');
//   // } else {
//   //   print('not verified');
//   //   await user?.sendEmailVerification();
//   // }
//   // await FirebaseAuth.instance.signOut();

//   runApp(const Firebasedemoapp());
// }

import 'package:demo_firebase/blocs/counter/counter_bloc.dart';
import 'package:demo_firebase/counter_page.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'firebase_options.dart'; // Generated by flutterfire CLI
import 'auth/login.dart'; // Your login screen

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Demo Firebase App',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: BlocProvider(
        create: (context) => CounterBloc(),
        child: CounterPage(),
      ), // Change to your first screen
    );
  }
}
